trigger:
  branches:
    include:
      - main

pr:
  - main

pool: 'contabo'

variables:
  buildConfiguration: 'Release'
  solutionName: 'semantic-release.sln'

stages:
  - stage: Variables
    jobs:
      - job:
        steps:
          - script: |
              echo $PATH
              env | sort

  - stage: Feature_branch
    condition: ne(variables['System.PullRequest.SourceBranch'], '')
    jobs:

      - job: build
        displayName: Building
        steps:
          - script: mvn clean compile

      - job: test
        displayName: Testing
        dependsOn: build
        steps:
          - script: mvn test

  - stage: Main_branch
    condition: and(eq(variables['System.PullRequest.SourceBranch'], ''), eq(variables['Build.SourceBranch'],'refs/heads/main'))
    jobs:

      - job: build
        displayName: Building
        steps:
          - script: mvn clean compile

      - job: test
        dependsOn: build
        displayName: Test solution
        steps:
          - script: mvn test

      - job: install_semantic
        dependsOn: test
        displayName: Install Semantic
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              npm install npm
            displayName: npm
          - script: |
              npm install semantic-release
            displayName: semantic-release
          - script: |
              npm install @semantic-release/changelog
            displayName: semantic-release/changelog
          - script: |
              npm install @semantic-release/exec
            displayName: semantic-release/exec
          - script: |
              npm install @semantic-release/git
            displayName: semantic-release/git
          - script: |
              npm install @semantic-release/github
            displayName: semantic-release/github
          - script: |
              pip3 install --user bump2version
            displayName: bump2version

      - job: semantic_release
        dependsOn: install_semantic
        displayName: Semantic Release
        steps:
          - script: |
              echo '##vso[task.prependpath]$(HOME)/.local/bin'
            displayName: PATH
          - script: |
              npx semantic-release
            displayName: semantic-release
            env:
              GH_TOKEN: $(githubToken)