trigger:
  branches:
    include:
      - main

pool: 'contabo'

stages:
  - stage: Variables
    jobs:
      - job:
        steps:
          - script: |
              echo $PATH
              env | sort
              mvn --version
              java -version

  - stage: Feature_branch
    condition: ne(variables['System.PullRequest.SourceBranch'], '')
    jobs:

      - job: build_solution
        displayName: Build Solution
        steps:
          - script: mvn clean compile -f pom.xml

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: mvn clean install -f pom.xml

      - job: sonar_analyze
        displayName: Sonar Analyze
        dependsOn: test_solution
        steps:
          - script: |
              mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.organization=$(SONAR_ORGANIZATION) \
              -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
              -Dsonar.host.url=$(SONAR_HOST_URL) \
              -Dsonar.login=$(SONAR_TOKEN) \
              -Dsonar.pullrequest.key=$(System.PullRequest.PullRequestNumber) \
              -Dsonar.pullrequest.branch=$(System.PullRequest.SourceBranch) \
              -Dsonar.pullrequest.base=main \
              -Dsonar.pullrequest.provider=GitHub \
              -Dsonar.pullrequest.github.repository=EncyclopediaGalactica/EG

  - stage: Main_branch
    condition: and(eq(variables['System.PullRequest.SourceBranch'], ''), eq(variables['Build.SourceBranch'],'refs/heads/main'))
    jobs:

      - job: build_solution
        displayName: Build Solution
        steps:
          - script: mvn clean compile -f pom.xml

      - job: test_solution
        displayName: Test Solution
        dependsOn: build_solution
        steps:
          - script: mvn clean install -f pom.xml

      - job: sonar_analyze
        displayName: Sonar Analyze
        dependsOn: test_solution
        steps:
          - script: |
              mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.organization=$(SONAR_ORGANIZATION) \
              -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
              -Dsonar.host.url=$(SONAR_HOST_URL) \
              -Dsonar.login=$(SONAR_TOKEN)
    