openapi: 3.0.3
info:
  title: SourceFormats
  description: Encyclopedia Galactica SourceFormats Api
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /sourceformat/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The SourceFormat Id identifies the object on which the operation will be executed
        schema:
          $ref: '#/components/schemas/SourceFormatId'

    get:
      description: Returns the defined SourceFormatDto object
      responses:
        '200':
          description: The defined SourceFormatDto object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceFormatDto'
    #    post:
    put:
      summary: Changes the designated SourceFormat object properties by the ones in the provided object
      requestBody:
        description: The provided SourceFormat object containing the new property values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceFormatDto'
      responses:
        200:
          description: Updating the designated SourceFormat object executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceFormatDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  
  
  #   delete:
  # /sourceformat/{parentId}/{childId}:
  #   post:
components:
  schemas:
    SourceFormatDto:
      description: SourceFormatDto object
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          description: the unique id of the SourceFormat object
          format: int64
          minimum: 0
        name:
          type: string
          description: the name of the SourceFormat object
          minLength: 3
          maxLength: 255
    
    SourceFormatId:
      type: integer
      format: int64
    
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
tags:
  
  
